services:
  database:
    container_name: "postgres_dev"
    image: "postgres:16.11-alpine3.23"
    env_file:
      - "../.env.development"
    ports:
      - "5432:5432"

  mainlcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher"
    ports:
      - "1025:1025"
      - "1080:1080"
